<a href='https://alexlenail.me/NN-SVG/'> NN visualization </a>

In [1]:
import torch
import torch.nn as nn

In [2]:
# torch.manual_seed(42)

In [4]:
fc1 = nn.Linear(1,2)

In [5]:
fc1

Linear(in_features=1, out_features=2, bias=True)

In [6]:
fc1.weight

Parameter containing:
tensor([[0.1524],
        [0.5845]], requires_grad=True)

In [7]:
fc1.bias

Parameter containing:
tensor([ 0.3014, -0.5731], requires_grad=True)

In [54]:
class Network(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(1, 1)
        # self.fc2 = nn.Linear(1,1)

    def forward(self, x):
        x = self.fc1(x)
        # x = self.fc2(x)

        return x

fc1 has one neuron. This one neuron receives one input. Neurons hold one weight for each input + one weight for bias (no matter how many inputs). In this case, how many weights and how many biases do we expect to have?

In [55]:
n = Network()

In [56]:
n.fc1

Linear(in_features=1, out_features=1, bias=True)

In [57]:
n.fc1.weight.shape

torch.Size([1, 1])

In [58]:
n.fc1.weight, n.fc1.bias

(Parameter containing:
 tensor([[0.4469]], requires_grad=True),
 Parameter containing:
 tensor([0.0837], requires_grad=True))

In [59]:
n = Network()
t = torch.tensor([1], dtype=torch.float32)
n(t)

tensor([0.3657], grad_fn=<ViewBackward0>)

In [62]:
n.fc1.weight.data.T

tensor([[-0.4109]])

In [63]:
n.fc1.bias.data

tensor([0.7766])

In [53]:
t @ n.fc1.weight.data.T + n.fc1.bias.data

tensor([-1.4963, -0.1710])

In [ ]:
t

In [ ]:
n.fc1.weight.data

In [ ]:
n.fc1.bias.data

In [92]:
class Network(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(1, 2)
        self.fc2 = nn.Linear(2,1)

    def forward(self, x):
        x = self.fc1(x)
        x = self.fc2(x)
        return x

This time, fc1 has 1 input and two outputs.

fc2 has 2 inputs and one input

In [93]:
n = Network()

How many weights and how many biases for fc1?

In [94]:
n.fc1.weight, n.fc1.bias

(Parameter containing:
 tensor([[ 0.2275],
         [-0.1189]], requires_grad=True),
 Parameter containing:
 tensor([ 0.9129, -0.7688], requires_grad=True))

How many weights and how many biases for fc2?

In [95]:
n.fc1.weight.shape, n.fc1.bias.shape

(torch.Size([2, 1]), torch.Size([2]))

In [96]:
n.fc2.weight, n.fc2.bias

(Parameter containing:
 tensor([[-0.0238,  0.0715]], requires_grad=True),
 Parameter containing:
 tensor([0.0231], requires_grad=True))

In [97]:
n = Network()
t = torch.tensor([1], dtype=torch.float32)
n(t)

tensor([-0.3031], grad_fn=<ViewBackward0>)

In [98]:
pytorch_res = n(t)
pytorch_res

tensor([-0.3031], grad_fn=<ViewBackward0>)

In [99]:
n.fc1.weight.data, n.fc1.bias.data

(tensor([[-0.5023],
         [-0.1162]]),
 tensor([-0.5331,  0.2996]))

In [100]:
fc1_weights = n.fc1.weight.data
fc1_biases = n.fc1.bias.data

In [101]:
fc1_biases

tensor([-0.5331,  0.2996])

In [102]:
t

tensor([1.])

In [103]:
fc1_weights

tensor([[-0.5023],
        [-0.1162]])

In [104]:
(t @ fc1_weights.T)

tensor([-0.5023, -0.1162])

In [ ]:
(t @ fc1_weights.T) + fc1_biases

In [106]:
fc1_res = t @ fc1_weights.T + fc1_biases
fc1_res

tensor([-1.0354,  0.1834])

In [107]:
fc2_weight = n.fc2.weight.data
fc2_bias = n.fc2.bias.data

In [109]:
fc1_res

tensor([-1.0354,  0.1834])

In [110]:
fc2_weight

tensor([[ 0.2647, -0.3894]])

In [113]:
-1.0354 * 0.2647 + 0.1834 * -0.3894

-0.34548634

In [114]:
fc1_res @ fc2_weight.T

tensor([-0.3455])

In [115]:
 fc2_bias

tensor([0.0424])

In [116]:
fc1_res @ fc2_weight.T + fc2_bias

tensor([-0.3031])

In [117]:
pytorch_res

tensor([-0.3031], grad_fn=<ViewBackward0>)

In [118]:
fc1_res @ fc2_weight.T + fc2_bias == pytorch_res

tensor([True])

In [119]:
class Network(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(1, 2)
        self.fc2 = nn.Linear(2,1)

    def forward(self, x):
        x = self.fc1(x)
        x = self.fc2(x)

        return x

In [120]:
n = Network()

In [121]:
t = torch.tensor([2], dtype=torch.float32)

In [123]:
n(t)

tensor([-0.0450], grad_fn=<ViewBackward0>)

In [124]:
n.fc1.weight.shape, n.fc2.weight.shape

(torch.Size([2, 1]), torch.Size([1, 2]))

In [125]:
n.fc1.bias, n.fc2.bias

(Parameter containing:
 tensor([0.3477, 0.9759], requires_grad=True),
 Parameter containing:
 tensor([-0.1724], requires_grad=True))

In [126]:
n.fc1.bias.shape, n.fc2.bias.shape

(torch.Size([2]), torch.Size([1]))

In [135]:
weights_1 = torch.tensor([[2.,3.]], requires_grad=True)
biases_1 = torch.tensor([4., 5.], requires_grad=True)            

weights_2 = torch.tensor([[2.], [3.]], requires_grad=True)
biases_2 = torch.tensor([4.], requires_grad=True)     

In [136]:
n.fc1.weight

Parameter containing:
tensor([[ 0.1516],
        [-0.4170]], requires_grad=True)

In [137]:
n.fc1.weight = nn.Parameter(weights_1.T)
n.fc1.bias = nn.Parameter(biases_1)

n.fc2.weight = nn.Parameter(weights_2.T)
n.fc2.bias = nn.Parameter(biases_2)

In [139]:
pytorch_res = n(t)
pytorch_res

tensor([53.], grad_fn=<ViewBackward0>)

In [140]:
n.fc1.weight.shape, n.fc2.weight.shape

(torch.Size([2, 1]), torch.Size([1, 2]))

In [141]:
n.fc1.bias.shape, n.fc2.bias.shape

(torch.Size([2]), torch.Size([1]))

In [142]:
n.fc1.weight

Parameter containing:
tensor([[2.],
        [3.]], requires_grad=True)

In [143]:
t

tensor([2.])

In [144]:
t @ n.fc1.weight.T

tensor([4., 6.], grad_fn=<SqueezeBackward4>)

In [146]:
n.fc1.bias

Parameter containing:
tensor([4., 5.], requires_grad=True)

In [147]:
fc1_res = t @ n.fc1.weight.T + n.fc1.bias

In [148]:
fc1_res

tensor([ 8., 11.], grad_fn=<AddBackward0>)

In [149]:
n.fc2.weight

Parameter containing:
tensor([[2., 3.]], requires_grad=True)

In [150]:
fc1_res.shape, n.fc2.weight.shape

(torch.Size([2]), torch.Size([1, 2]))

In [151]:
8 * 2 + 11 * 3

49

In [152]:
n.fc2.bias

Parameter containing:
tensor([4.], requires_grad=True)

In [153]:
fc1_res @ n.fc2.weight.T

tensor([49.], grad_fn=<SqueezeBackward4>)

In [154]:
n.fc2.bias

Parameter containing:
tensor([4.], requires_grad=True)

In [155]:
fc2_res = fc1_res @ n.fc2.weight.T + n.fc2.bias
fc2_res

tensor([53.], grad_fn=<AddBackward0>)

In [156]:
fc2_res == pytorch_res

tensor([True])